/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://ymhh3eg4qfhixolj52zfj3rvme.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-6vinhgoopfenlcum3oqoi7abmq",
    "aws_cognito_identity_pool_id": "us-east-1:d03de99a-c906-4eea-9b91-a08c8c33d675",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_yvMb5OWPV",
    "aws_user_pools_web_client_id": "45uiegre51qtvk7o952e09kjet",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "enkassite-storage-958c80d5185507-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
